### ISSUE TITLE
请问这个代码是什么错误，应该怎么修改

### ISSUE THREAD

**Issue by zwdzwdzwd** [resphinas/claude-on-wechat#6]
尝试部署到railway上，更改了 
1 claude_api.py 中的
self.org_uuid = 改为自己的org id
self.con_uuid = 改为自己的 con id

2 config.json 中的 
"org_uuid":改为自己的org id
"con_uuid":改为自己的 con id
 "cookie":改为自己的 聊天cookie，利用edit this cookie 插件导出的cookie

3 config.py 中的
"org_uuid":改为自己的org id
"con_uuid":改为自己的 con id
 "cookie":改为自己的 聊天cookie，利用edit this cookie 插件导出的cookie

railway部署好后 出现二维码，用微信扫码登录后出现这个错误，

[ERROR][2023-08-22 16:07:07][app.py:52] - App startup failed!
﻿
[ERROR][2023-08-22 16:07:07][app.py:53] - 'wxsid'
﻿
Traceback (most recent call last):
﻿
File "/app/app.py", line 50, in run
﻿
channel.startup()
﻿
File "/app/channel/wechat/wechat_channel.py", line 118, in startup
﻿
itchat.auto_login(
﻿
File "/app/lib/itchat/components/register.py", line 38, in auto_login
﻿
self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
﻿
File "/app/lib/itchat/components/login.py", line 61, in login
﻿
status = self.check_login()
﻿
File "/app/lib/itchat/components/login.py", line 154, in check_login
﻿
if process_login_info(self, r.text):
﻿
File "/app/lib/itchat/components/login.py", line 206, in process_login_info
﻿
core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
﻿
KeyError: 'wxsid'

现在不知道改怎么办了，希望可以帮忙看看，谢谢！

**Comment by resphinas** [comment]
这个问题是 因为 你使用登录的微信号需要绑定一张银行卡才行，微信组件库的问题，不过现在项目失效了，根本原因是官方使用了cloudware作为反爬虫手段，目前还没发现有人破解出来，可以尝试用selenium自动化项目平替，github上应该有相关项目

**Comment by resphinas** [comment]
可以用了哦
